apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: acme@email.com
    http01: {}
    privateKeySecretRef:
      name: issuer-private-key-secret
    server: https://acme-v02.api.letsencrypt.org/directory
