apiVersion: v1
kind: Service
metadata:
  name: smartfox-deployment-service
  namespace: smartfox
spec:
  type: ClusterIP
  selector:
    app: smartfox-deployment
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 8787
      targetPort: 8787
      name: tcp2
    - port: 5000
      targetPort: 5000
      name: tcp3
---
apiVersion: v1
kind: Service
metadata:
  name: smartfox-deployment-loadbalancer
  namespace: smartfox
spec:
  type: LoadBalancer
  selector:
    app: smartfox-deployment
  ports:
    - port: 9933
      targetPort: 9933
      name: tcp
