apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: smartfox-deployment
  name: smartfox-deployment
  namespace: smartfox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartfox-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: smartfox-deployment
    spec:
      containers:
      - env:
        - name: EXAMPLE_ENV
          value: example
        - name: EXAMPLE_ENV2
          value: example2
        image: timlien/docker-smartfox:latest
        imagePullPolicy: IfNotPresent
        name: smartfox-deployment
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
