apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rethinkdb-master
  namespace: rethinkdb
spec:
  serviceName: rethinkdb-master
  replicas: 1
  template:
    metadata:
      labels:
        app: rethinkdb-master
    spec:
      hostname: rethinkdb-master
      containers:
      - name: rethinkdb
        image: rethinkdb:2.4
        # set the canonical address for this node to a custom one
        command: ["rethinkdb"]
        args:
        - --bind
        - "all"
        - --canonical-address
        - "rethinkdb-master:29015"
        - --canonical-address
        - "$(MY_POD_IP):29015"
        volumeMounts:
        - name: rethinkdb-pv
          mountPath: /data
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      volumes:
      - name: rethinkdb-pv
        hostPath:
          path: /var/data/rethinkdb
